// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace FirstIssue.WebApp.Controllers
{
    public partial class MagazineController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MagazineController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected MagazineController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult GetPrebuiltStyle()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetPrebuiltStyle);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MagazineController Actions { get { return MVC.Magazine; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Magazine";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Magazine";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ListMagazines = "ListMagazines";
            public readonly string StyleCreator = "StyleCreator";
            public readonly string GetPrebuiltStyle = "GetPrebuiltStyle";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ListMagazines = "ListMagazines";
            public const string StyleCreator = "StyleCreator";
            public const string GetPrebuiltStyle = "GetPrebuiltStyle";
        }


        static readonly ActionParamsClass_GetPrebuiltStyle s_params_GetPrebuiltStyle = new ActionParamsClass_GetPrebuiltStyle();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPrebuiltStyle GetPrebuiltStyleParams { get { return s_params_GetPrebuiltStyle; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPrebuiltStyle
        {
            public readonly string prebuiltStyleId = "prebuiltStyleId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ListMagazines = "ListMagazines";
                public readonly string StyleCreator = "StyleCreator";
            }
            public readonly string ListMagazines = "~/Views/Magazine/ListMagazines.cshtml";
            public readonly string StyleCreator = "~/Views/Magazine/StyleCreator.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_MagazineController : FirstIssue.WebApp.Controllers.MagazineController
    {
        public T4MVC_MagazineController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ViewResult ListMagazines()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.ListMagazines);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult StyleCreator()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StyleCreator);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult GetPrebuiltStyle(int prebuiltStyleId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetPrebuiltStyle);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "prebuiltStyleId", prebuiltStyleId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
